// ══════════════════════════════════════════════
// LIVE CALL — full Phone Call mode (§19.2). Habooba answers dynamically,
// every turn generated by Claude but heavily few-shot grounded against the
// verified call transcripts so the dialect stays real. Coaching arrives as
// quiet whispers outside the conversation — habooba never corrects you.
// Unlocks once Family reaches Comfortable (progressive unlock, §13).
// ══════════════════════════════════════════════

let lcHistory = [];      // [{who:'family'|'you', ar, ph, en, whisper?}]
let lcInput = '';
let lcBusy = false;
let lcDone = false;
let lcError = null;

function lcUnlocked() { return domainTier('family') !== 'Beginning'; }
function lcTurnCount() { return lcHistory.filter(h => h.who === 'you').length; }

function lcReset() {
  lcHistory = []; lcInput = ''; lcBusy = false; lcDone = false; lcError = null;
}

function renderLivecall() {
  const ca = document.getElementById('content-area');

  if (!lcUnlocked()) {
    ca.innerHTML = `
      <div class="coach-wrap">
        <button class="d2-back" onclick="setMode('home')">← home</button>
        <div class="d2-card" style="text-align:center">
          <div style="font-size:34px">🔒</div>
          <div class="c2-title" style="margin:10px 0 6px">Habooba's line opens with comfort</div>
          <div class="d2-note" style="margin:0 auto;max-width:380px">A live call is the deep end — finish the Family basics in Guided practice first, then habooba picks up.</div>
          <div class="d2-pill-row" style="margin-top:16px">
            <button class="d2-pill-gold" onclick="setFocusDomain('family');setMode('guided')">Back to Guided →</button>
          </div>
        </div>
      </div>`;
    return;
  }

  const configured = apiConfigured();
  const started = lcHistory.length > 0;

  ca.innerHTML = `
    <div class="coach-wrap">
      <button class="d2-back" onclick="setMode('home')">← home</button>
      <div class="c2-head">
        <div>
          <div class="c2-title">📞 Live call · حبوبة</div>
          <div class="c2-sub">she answers for real this time — grounded on the verified calls, never invented</div>
        </div>
      </div>

      ${!started ? `
      <div class="d2-card" style="text-align:center">
        <span class="intro-orb" style="margin:0 auto"><tariga-orb mode="idle"></tariga-orb></span>
        <div class="c2-title" style="font-size:19px;margin:14px 0 6px">Call habooba</div>
        <div class="d2-note" style="margin:0 auto 4px;max-width:380px">A real back-and-forth — she asks, you answer, the call goes where you take it. Gentle coaching whispers appear under your turns; habooba herself never corrects you.</div>
        <div class="d2-pill-row" style="margin-top:14px">
          <button class="c2-compare" onclick="lcStart()" ${configured ? '' : 'disabled title="Connect the coach first (in Your coach)"'}>📞 Call now</button>
        </div>
        ${configured ? '' : '<div class="d2-note" style="margin-top:8px">connect the coach in <b>Your coach</b> first</div>'}
      </div>` : `
      <div class="d2-thread">
        ${lcHistory.map(h => `
          <div class="d2-msg ${h.who === 'family' ? 'host' : 'guest'}">
            <div class="d2-msg-who">${h.who === 'family' ? 'حبوبة' : 'You'}</div>
            <div class="d2-bubble" style="cursor:default">
              <div class="d2-bubble-ar">${escAttr(h.ar || h.text || '')}</div>
              ${h.ph ? `<div class="d2-bubble-ph">${escAttr(h.ph)}</div>` : ''}
              ${h.en ? `<div class="d2-bubble-en">${escAttr(h.en)}</div>` : ''}
              ${h.who === 'family' && h.ar ? `<div style="text-align:left;margin-top:6px">${speakerSVG('#a09e9a', encodeURIComponent(h.ar))}</div>` : ''}
            </div>
            ${h.whisper ? `<div class="lc-whisper">🤫 ${escAttr(h.whisper)}</div>` : ''}
          </div>`).join('')}
        ${lcBusy ? `
          <div class="d2-msg host">
            <div class="d2-msg-who">حبوبة</div>
            <div class="d2-bubble" style="cursor:default"><div class="c2-dots" style="height:16px"><span></span><span></span><span></span><span></span></div></div>
          </div>` : ''}
      </div>

      ${lcDone ? `
        <div class="d2-gold-box" style="text-align:center">
          <div class="c2-title" style="font-size:19px">She hung up smiling. 🤍</div>
          <div class="d2-when-body" style="margin-top:8px">${lcTurnCount()} turns of real conversation — that's the whole point of everything else in this app.</div>
        </div>
        <div class="d2-pill-row">
          <button class="c2-ghost-pill" onclick="lcStart()">📞 Call again</button>
          <button class="d2-pill-gold" onclick="setMode('home')">Done →</button>
        </div>
      ` : !lcBusy ? `
        <div class="c2-textbox" style="margin-top:14px">
          <textarea id="lc-input" dir="auto" rows="2" placeholder="answer her — Arabic, Arabizi, or even English (she'll stay in Sudanese)"></textarea>
          <div class="c2-textbox-row">
            ${coachMicSupported() ? `<button class="c2-mic-small" id="lc-mic" onclick="lcMic()">🎙</button>` : ''}
            <span style="flex:1"></span>
            <button class="c2-compare" onclick="lcSend()">Say it →</button>
          </div>
        </div>
      ` : ''}
      ${lcError ? `<div class="coach-error">${escAttr(lcError)}</div>` : ''}
      `}
    </div>
  `;
  const ta = document.getElementById('lc-input');
  if (ta) {
    ta.value = lcInput;
    ta.addEventListener('input', () => { lcInput = ta.value; });
    ta.focus();
  }
}

function lcMic() {
  prodMic('lc-mic', (t) => {
    lcInput = (lcInput ? lcInput.trimEnd() + ' ' : '') + t;
    const ta = document.getElementById('lc-input');
    if (ta) ta.value = lcInput;
  });
}

async function lcStart() {
  lcReset();
  lcBusy = true;
  renderLivecall();
  await lcTurn(null);   // habooba opens the call
}

async function lcSend() {
  const ta = document.getElementById('lc-input');
  lcInput = (ta ? ta.value : lcInput).trim();
  if (!lcInput || lcBusy) { if (ta) ta.focus(); return; }
  const text = lcInput;
  lcHistory.push({ who: 'you', text, ar: text });
  lcInput = '';
  lcBusy = true;
  renderLivecall();
  await lcTurn(text);
}

async function lcTurn(userText) {
  const maxTurns = TARIGA_CONFIG.livecall.maxTurns;
  try {
    const req = buildLiveCallRequest(lcHistory, userText, lcTurnCount(), maxTurns);
    const out = await coachEvaluate(req);
    // whisper attaches under the learner's last turn, outside the conversation
    if (userText && out.coach_whisper) {
      const lastYou = [...lcHistory].reverse().find(h => h.who === 'you');
      if (lastYou) lastYou.whisper = out.coach_whisper;
    }
    lcHistory.push({ who: 'family', ...out.reply });
    lcDone = !!out.call_done || lcTurnCount() >= maxTurns;
    if (lcDone) { recordActivity(); if (typeof logEvent === 'function') logEvent('livecall_done', { turns: lcTurnCount() }); }
  } catch (e) {
    lcError = 'The line dropped (' + (e.message || e) + ') — try again.';
    if (userText) lcHistory.pop(); // give the learner their turn back
    lcInput = userText || '';
  }
  lcBusy = false;
  renderLivecall();
}
